import { defineContent } from "@/lib/schemas/common";
import { systemGraph } from "@/lib/schemas/graph";

export const reactArchitectureGraph = defineContent("graphs/react-architecture", systemGraph, {
  id: "react-architecture",
  title: "React application architecture",
  description:
    "Seven layers with one-directional dependencies, from what users see down to the backend.",
  layers: [
    "UI",
    "Feature Modules",
    "Reusable Components",
    "Hooks",
    "State / Query",
    "API Layer",
    "Backend",
  ],
  nodes: [
    {
      id: "ui",
      label: "UI",
      kind: "application",
      summary: "Routes and layouts that compose features into pages.",
      details: {
        responsibility: "Page composition, routing, layout.",
        whyItMatters: "Keeps pages thin so features stay reusable.",
      },
      layout: { x: 50, y: 4 },
      layer: 0,
    },
    {
      id: "features",
      label: "Feature Modules",
      kind: "module",
      summary: "Self-contained business capabilities (e.g. checkout, inspection).",
      details: {
        responsibility: "Own a feature's components, hooks and state.",
        whyItMatters: "Teams can change one feature without touching others.",
        tradeoffs: ["Some duplication is cheaper than the wrong shared abstraction"],
      },
      layout: { x: 50, y: 19 },
      layer: 1,
    },
    {
      id: "components",
      label: "Reusable Components",
      kind: "component",
      summary: "Design-system primitives with no business logic.",
      details: {
        responsibility: "Accessible, themeable building blocks.",
        whyItMatters: "Consistency and accessibility are solved once.",
        tradeoffs: ["Must never import from features"],
      },
      layout: { x: 50, y: 34 },
      layer: 2,
    },
    {
      id: "hooks",
      label: "Hooks",
      kind: "module",
      summary: "Reusable behavior: data access, subscriptions, UI logic.",
      details: {
        responsibility: "Encapsulate effects and stateful logic.",
        whyItMatters: "Components stay declarative and testable.",
      },
      layout: { x: 50, y: 49 },
      layer: 3,
    },
    {
      id: "state",
      label: "State / Query",
      kind: "module",
      summary: "Server state in a query cache; client state kept local or in a small store.",
      details: {
        responsibility: "Caching, invalidation, optimistic updates.",
        whyItMatters: "Most 'global state' is really cached server data.",
        tradeoffs: ["A global store for everything causes needless re-renders"],
      },
      layout: { x: 50, y: 64 },
      layer: 4,
    },
    {
      id: "api",
      label: "API Layer",
      kind: "api",
      summary: "Typed client functions; one place for auth headers, errors and retries.",
      details: {
        responsibility: "Translate HTTP into typed domain data.",
        whyItMatters: "Backend changes stay contained in one layer.",
      },
      layout: { x: 50, y: 79 },
      layer: 5,
    },
    {
      id: "backend",
      label: "Backend",
      kind: "external",
      summary: "REST or GraphQL services the app depends on.",
      layout: { x: 50, y: 95 },
      layer: 6,
    },
  ],
  edges: [
    { id: "ui-features", from: "ui", to: "features", kind: "dependency" },
    { id: "features-components", from: "features", to: "components", kind: "dependency" },
    { id: "features-hooks", from: "features", to: "hooks", kind: "dependency" },
    { id: "components-hooks", from: "components", to: "hooks", kind: "dependency" },
    { id: "hooks-state", from: "hooks", to: "state", kind: "dataFlow" },
    { id: "state-api", from: "state", to: "api", kind: "request" },
    { id: "api-backend", from: "api", to: "backend", kind: "request" },
  ],
  trace: ["ui-features", "features-hooks", "hooks-state", "state-api", "api-backend"],
});

export const nextjsRenderingGraph = defineContent("graphs/nextjs-rendering", systemGraph, {
  id: "nextjs-rendering",
  title: "Next.js rendering paths",
  description:
    "Where and when HTML is produced for each rendering strategy. Choose a strategy to highlight its path.",
  layers: ["Build", "Delivery", "Client"],
  nodes: [
    {
      id: "data",
      label: "Data Source",
      kind: "database",
      summary: "CMS, database or API that pages read from.",
      layout: { x: 12, y: 10 },
      layer: 0,
    },
    {
      id: "build",
      label: "Build",
      kind: "module",
      summary: "next build prerenders static routes ahead of time.",
      layout: { x: 50, y: 10 },
      layer: 0,
    },
    {
      id: "server",
      label: "Server",
      kind: "application",
      summary: "Renders Server Components and dynamic routes per request.",
      layout: { x: 26, y: 50 },
      layer: 1,
    },
    {
      id: "cdn",
      label: "CDN Cache",
      kind: "external",
      summary: "Serves prerendered HTML and assets from the edge.",
      layout: { x: 74, y: 50 },
      layer: 1,
    },
    {
      id: "browser",
      label: "Browser",
      kind: "application",
      summary: "Paints HTML, then hydrates Client Components.",
      layout: { x: 50, y: 90 },
      layer: 2,
    },
  ],
  edges: [
    { id: "data-build", from: "data", to: "build", kind: "dataFlow" },
    { id: "data-server", from: "data", to: "server", kind: "dataFlow" },
    { id: "build-cdn", from: "build", to: "cdn", kind: "dataFlow", label: "static HTML" },
    { id: "server-cdn", from: "server", to: "cdn", kind: "dataFlow", label: "revalidate" },
    {
      id: "server-browser",
      from: "server",
      to: "browser",
      kind: "dataFlow",
      label: "streamed HTML / RSC",
    },
    { id: "cdn-browser", from: "cdn", to: "browser", kind: "dataFlow" },
    { id: "browser-data", from: "browser", to: "data", kind: "request", label: "client fetch" },
  ],
  lenses: [
    {
      id: "server-components",
      label: "Server Components",
      note: "Rendered on the server; their code never ships to the browser.",
      emphasize: { nodes: ["data", "server", "browser"], edges: ["data-server", "server-browser"] },
    },
    {
      id: "client-components",
      label: "Client Components",
      note: "Prerendered as HTML, then hydrated in the browser for interactivity.",
      emphasize: { nodes: ["server", "browser"], edges: ["server-browser"] },
    },
    {
      id: "ssr",
      label: "SSR",
      note: "Rendered per request: always fresh, costs server time on every visit.",
      emphasize: { nodes: ["data", "server", "browser"], edges: ["data-server", "server-browser"] },
    },
    {
      id: "ssg",
      label: "SSG",
      note: "Rendered once at build and served from the CDN: fastest, stale until rebuilt.",
      emphasize: {
        nodes: ["data", "build", "cdn", "browser"],
        edges: ["data-build", "build-cdn", "cdn-browser"],
      },
    },
    {
      id: "isr",
      label: "ISR",
      note: "Static at build, then regenerated in the background after a revalidation window or on demand.",
      emphasize: {
        nodes: ["build", "server", "cdn", "browser"],
        edges: ["build-cdn", "server-cdn", "cdn-browser"],
      },
    },
    {
      id: "csr",
      label: "CSR",
      note: "A static shell loads, then the browser fetches data and renders. Fine behind login; weak for SEO and LCP.",
      emphasize: { nodes: ["cdn", "browser", "data"], edges: ["cdn-browser", "browser-data"] },
    },
  ],
});

const remotes = ["a", "b", "c"] as const;

export const microFrontendsGraph = defineContent("graphs/micro-frontends", systemGraph, {
  id: "micro-frontends",
  title: "Micro frontends with Module Federation",
  description:
    "A host shell composes independently deployed remotes at runtime. Choose a lens to see each concern.",
  layers: ["Host shell", "Remotes", "Shared platform"],
  nodes: [
    {
      id: "host",
      label: "Host",
      kind: "application",
      summary: "Shell app: routing, layout, auth session; loads remotes on demand.",
      details: { responsibility: "Composition, top-level routing, error boundaries." },
      layout: { x: 50, y: 10 },
      layer: 0,
    },
    ...remotes.map((r, i) => ({
      id: `remote-${r}`,
      label: `Remote ${r.toUpperCase()}`,
      kind: "module" as const,
      summary: `Feature area owned and deployed by Team ${r.toUpperCase()}.`,
      details: { responsibility: "Exposes modules via a remoteEntry manifest." },
      layout: { x: 20 + i * 30, y: 46 },
      layer: 1,
    })),
    {
      id: "shared",
      label: "Shared Deps",
      kind: "module",
      summary: "Singletons like React and the design system, negotiated at runtime.",
      details: { tradeoffs: ["Version drift across remotes", "Must agree on singleton ranges"] },
      layout: { x: 30, y: 84 },
      layer: 2,
    },
    {
      id: "auth",
      label: "Auth / Session",
      kind: "api",
      summary: "Session owned by the host and passed to remotes.",
      layout: { x: 14, y: 10 },
      layer: 2,
    },
    {
      id: "events",
      label: "Event Bus",
      kind: "component",
      summary: "Loose, typed events for cross-remote communication.",
      layout: { x: 70, y: 95 },
      layer: 2,
    },
    {
      id: "cdn",
      label: "Remote CDN",
      kind: "external",
      summary: "Hosts each remote's versioned bundles and manifest.",
      layout: { x: 86, y: 10 },
      layer: 2,
    },
  ],
  edges: [
    ...remotes.map((r) => ({
      id: `host-${r}`,
      from: "host",
      to: `remote-${r}`,
      kind: "dependency" as const,
      label: "loads at runtime",
    })),
    ...remotes.map((r) => ({
      id: `${r}-shared`,
      from: `remote-${r}`,
      to: "shared",
      kind: "dependency" as const,
    })),
    ...remotes.map((r) => ({
      id: `${r}-events`,
      from: `remote-${r}`,
      to: "events",
      kind: "event" as const,
    })),
    { id: "host-auth", from: "host", to: "auth", kind: "request" },
    { id: "cdn-host", from: "cdn", to: "host", kind: "dataFlow", label: "remoteEntry.js" },
  ],
  lenses: [
    {
      id: "module-federation",
      label: "Module Federation",
      note: "The host fetches each remote's manifest from the CDN and imports exposed modules at runtime.",
      emphasize: {
        nodes: ["host", "remote-a", "remote-b", "remote-c", "cdn"],
        edges: ["host-a", "host-b", "host-c", "cdn-host"],
      },
    },
    {
      id: "shared-deps",
      label: "Shared dependencies",
      note: "React and the design system load once as singletons so remotes don't each ship their own copy.",
      emphasize: {
        nodes: ["shared", "remote-a", "remote-b", "remote-c"],
        edges: ["a-shared", "b-shared", "c-shared"],
      },
    },
    {
      id: "independent-deploy",
      label: "Independent deployment",
      note: "Each remote publishes to the CDN on its own pipeline; the host picks it up without a redeploy.",
      emphasize: { nodes: ["remote-a", "remote-b", "remote-c", "cdn"], edges: ["cdn-host"] },
    },
    {
      id: "team-ownership",
      label: "Team ownership",
      note: "Boundaries follow teams and business domains, not technical layers.",
      emphasize: { nodes: ["remote-a", "remote-b", "remote-c"], edges: [] },
    },
    {
      id: "versioning",
      label: "Version compatibility",
      note: "Shared singletons need agreed semver ranges; contracts between host and remotes are versioned.",
      emphasize: { nodes: ["shared"], edges: ["a-shared", "b-shared", "c-shared"] },
    },
    {
      id: "routing",
      label: "Routing",
      note: "The host owns top-level routes; remotes own the routes inside their area.",
      emphasize: {
        nodes: ["host", "remote-a", "remote-b", "remote-c"],
        edges: ["host-a", "host-b", "host-c"],
      },
    },
    {
      id: "auth",
      label: "Authentication",
      note: "One session in the host; remotes receive identity rather than re-authenticating.",
      emphasize: { nodes: ["host", "auth"], edges: ["host-auth"] },
    },
    {
      id: "communication",
      label: "Communication",
      note: "Remotes talk through typed events or URL state, never by importing each other.",
      emphasize: { nodes: ["events"], edges: ["a-events", "b-events", "c-events"] },
    },
    {
      id: "failure-isolation",
      label: "Failure isolation",
      note: "Each remote mounts inside an error boundary with a fallback, so one failing remote doesn't take down the shell.",
      emphasize: { nodes: ["host", "remote-b"], edges: ["host-b"] },
    },
    {
      id: "performance",
      label: "Performance",
      note: "Shared singletons, preloading likely remotes and caching manifests keep runtime composition fast.",
      emphasize: {
        nodes: ["shared", "cdn"],
        edges: ["cdn-host", "a-shared", "b-shared", "c-shared"],
      },
    },
  ],
});

export const apiArchitectureGraph = defineContent("graphs/api-architecture", systemGraph, {
  id: "api-architecture",
  title: "API request lifecycle",
  description:
    "A request passes through the API layer, authentication and business logic to data and external services.",
  layers: ["Client", "Edge", "Security", "Domain", "Data"],
  nodes: [
    {
      id: "client",
      label: "Client",
      kind: "application",
      summary: "Browser or mobile app calling the API.",
      layout: { x: 50, y: 5 },
      layer: 0,
    },
    {
      id: "api-layer",
      label: "API Layer",
      kind: "api",
      summary: "Routing, validation, rate limiting and response shaping.",
      details: { responsibility: "Reject bad input early; keep a stable contract." },
      layout: { x: 50, y: 27 },
      layer: 1,
    },
    {
      id: "auth",
      label: "Authentication",
      kind: "module",
      summary: "Verifies identity and permissions before any business logic runs.",
      layout: { x: 50, y: 49 },
      layer: 2,
    },
    {
      id: "logic",
      label: "Business Logic",
      kind: "module",
      summary: "Domain rules, kept independent of HTTP and storage details.",
      details: { whyItMatters: "Testable without a server or database." },
      layout: { x: 50, y: 71 },
      layer: 3,
    },
    {
      id: "db",
      label: "Database",
      kind: "database",
      summary: "Persistent state, accessed through a repository layer.",
      layout: { x: 30, y: 94 },
      layer: 4,
    },
    {
      id: "external",
      label: "External Services",
      kind: "external",
      summary: "Payments, email, storage and other third-party APIs.",
      details: { tradeoffs: ["Timeouts, retries and circuit breakers are required"] },
      layout: { x: 70, y: 94 },
      layer: 4,
    },
  ],
  edges: [
    { id: "client-api", from: "client", to: "api-layer", kind: "request" },
    { id: "api-auth", from: "api-layer", to: "auth", kind: "request" },
    { id: "auth-logic", from: "auth", to: "logic", kind: "request" },
    { id: "logic-db", from: "logic", to: "db", kind: "dataFlow" },
    { id: "logic-external", from: "logic", to: "external", kind: "request" },
  ],
  trace: ["client-api", "api-auth", "auth-logic", "logic-db", "logic-external"],
});
