import { defineContent } from "@/lib/schemas/common";
import { systemGraph } from "@/lib/schemas/graph";

export const techEcosystemGraph = defineContent("graphs/tech-ecosystem", systemGraph, {
  id: "tech-ecosystem",
  title: "Technology ecosystem",
  description:
    "How the core technologies relate, from the React ecosystem down to cloud infrastructure.",
  layers: ["Core", "React ecosystem", "Backend", "Interface", "Data", "Cloud"],
  nodes: [
    {
      id: "react",
      label: "React",
      kind: "module",
      summary: "Component model at the center of the frontend stack.",
      layout: { x: 50, y: 5 },
      layer: 0,
    },
    {
      id: "redux",
      label: "Redux Toolkit",
      kind: "module",
      summary: "Predictable client state for complex workflows.",
      layout: { x: 10, y: 24 },
      layer: 1,
    },
    {
      id: "react-query",
      label: "React Query",
      kind: "module",
      summary: "Server-state caching, invalidation and background refresh.",
      layout: { x: 36, y: 24 },
      layer: 1,
    },
    {
      id: "nextjs",
      label: "Next.js",
      kind: "application",
      summary: "Routing, server rendering and performance on top of React.",
      layout: { x: 63, y: 24 },
      layer: 1,
    },
    {
      id: "typescript",
      label: "TypeScript",
      kind: "module",
      summary: "Types shared across frontend and backend.",
      layout: { x: 90, y: 24 },
      layer: 1,
    },
    {
      id: "node",
      label: "Node.js",
      kind: "application",
      summary: "Services with Express and NestJS.",
      layout: { x: 70, y: 44 },
      layer: 2,
    },
    {
      id: "apis",
      label: "APIs",
      kind: "api",
      summary: "REST, GraphQL and real-time (WebSockets / Socket.IO).",
      layout: { x: 50, y: 63 },
      layer: 3,
    },
    {
      id: "databases",
      label: "Databases",
      kind: "database",
      summary: "PostgreSQL, MySQL and MongoDB.",
      layout: { x: 50, y: 80 },
      layer: 4,
    },
    {
      id: "aws",
      label: "AWS",
      kind: "external",
      summary: "Hosting, containers and managed services; Docker and CI/CD.",
      layout: { x: 50, y: 96 },
      layer: 5,
    },
  ],
  edges: [
    { id: "react-redux", from: "react", to: "redux", kind: "dependency" },
    { id: "react-to-query", from: "react", to: "react-query", kind: "dependency" },
    { id: "react-nextjs", from: "react", to: "nextjs", kind: "dependency" },
    { id: "react-typescript", from: "react", to: "typescript", kind: "dependency" },
    { id: "typescript-node", from: "typescript", to: "node", kind: "dependency" },
    { id: "nextjs-apis", from: "nextjs", to: "apis", kind: "request" },
    { id: "query-apis", from: "react-query", to: "apis", kind: "request" },
    { id: "node-apis", from: "node", to: "apis", kind: "dependency", label: "serves" },
    { id: "apis-databases", from: "apis", to: "databases", kind: "dataFlow" },
    { id: "databases-aws", from: "databases", to: "aws", kind: "dependency", label: "hosted on" },
  ],
});
