import { defineContent } from "@/lib/schemas/common";
import { systemGraph } from "@/lib/schemas/graph";

export const techEcosystemGraph = defineContent("graphs/tech-ecosystem", systemGraph, {
  id: "tech-ecosystem",
  title: "Technology ecosystem",
  description:
    "One typed language across the stack: a React frontend and Node.js backend meet at the API, on top of data and cloud infrastructure.",
  layers: ["Language", "Runtimes", "Frameworks & libraries", "Interface", "Data", "Cloud"],
  nodes: [
    {
      id: "typescript",
      label: "TypeScript",
      kind: "module",
      summary:
        "One typed language from the component to the service, with types shared across both.",
      layout: { x: 50, y: 5 },
      layer: 0,
    },
    {
      id: "react",
      label: "React",
      kind: "module",
      summary: "Component model for the interface.",
      layout: { x: 30, y: 24 },
      layer: 1,
    },
    {
      id: "node",
      label: "Node.js",
      kind: "application",
      summary: "Server runtime for services and APIs.",
      layout: { x: 76, y: 24 },
      layer: 1,
    },
    {
      id: "redux",
      label: "Redux Toolkit",
      kind: "module",
      summary: "Predictable client state for complex workflows.",
      layout: { x: 9, y: 44 },
      layer: 2,
    },
    {
      id: "react-query",
      label: "React Query",
      kind: "module",
      summary: "Server-state caching, invalidation and background refresh.",
      layout: { x: 30, y: 44 },
      layer: 2,
    },
    {
      id: "nextjs",
      label: "Next.js",
      kind: "application",
      summary: "Routing, server rendering and performance on top of React.",
      layout: { x: 51, y: 44 },
      layer: 2,
    },
    {
      id: "frameworks",
      label: "Express / NestJS",
      kind: "application",
      summary: "Service frameworks for REST and GraphQL APIs, auth and validation.",
      layout: { x: 76, y: 44 },
      layer: 2,
    },
    {
      id: "apis",
      label: "APIs",
      kind: "api",
      summary: "REST, GraphQL and real-time (WebSockets / Socket.IO).",
      layout: { x: 50, y: 63 },
      layer: 3,
    },
    {
      id: "databases",
      label: "Databases",
      kind: "database",
      summary: "PostgreSQL, MySQL and MongoDB.",
      layout: { x: 50, y: 80 },
      layer: 4,
    },
    {
      id: "aws",
      label: "AWS",
      kind: "external",
      summary: "Hosting and managed services, with Docker, Kubernetes and GitLab CI/CD.",
      layout: { x: 50, y: 96 },
      layer: 5,
    },
  ],
  edges: [
    { id: "typescript-react", from: "typescript", to: "react", kind: "dependency" },
    { id: "typescript-node", from: "typescript", to: "node", kind: "dependency" },
    { id: "react-redux", from: "react", to: "redux", kind: "dependency" },
    { id: "react-to-query", from: "react", to: "react-query", kind: "dependency" },
    { id: "react-nextjs", from: "react", to: "nextjs", kind: "dependency" },
    { id: "node-frameworks", from: "node", to: "frameworks", kind: "dependency" },
    { id: "nextjs-apis", from: "nextjs", to: "apis", kind: "request" },
    { id: "query-apis", from: "react-query", to: "apis", kind: "request" },
    { id: "frameworks-apis", from: "frameworks", to: "apis", kind: "dependency", label: "serves" },
    { id: "apis-databases", from: "apis", to: "databases", kind: "dataFlow" },
    { id: "databases-aws", from: "databases", to: "aws", kind: "dependency", label: "hosted on" },
  ],
});
