import { defineContent } from "@/lib/schemas/common";
import { experienceSchema } from "@/lib/schemas/content";

/**
 * Companies, titles, dates and bullets are taken from Deepak's resume
 * (public/resume/deepak-gupta-resume.pdf). Anything it doesn't state is
 * listed in `pending` until supplied. Newest first.
 */
export const experience = defineContent("experience", experienceSchema, [
  {
    id: "techblocks",
    company: "TechBlocks",
    title: "Senior Software Engineer",
    period: { start: "2026-06", end: "2026-07" },
    location: "Hyderabad, India",
    summary: null,
    responsibilities: [
      "Completed organizational onboarding and engineering enablement for enterprise software development, covering development standards, engineering workflows, source control, CI/CD, testing, and delivery practices.",
      "Participated in pre-project engineering activities covering application architecture, environment management, code quality, testing practices, release processes, and project readiness.",
      "Collaborated with engineering teams on development workflows, CI/CD processes, code reviews, environment readiness, and release-readiness activities.",
    ],
    technologies: [],
    focus: ["Engineering standards", "CI/CD", "Code quality", "Release readiness"],
    achievements: [],
    projects: [],
    pending: ["Technologies used", "Key achievements"],
  },
  {
    id: "nagarro-senior",
    company: "Nagarro",
    title: "Senior Software Engineer",
    period: { start: "2024-07", end: "2026-03" },
    location: null,
    summary: null,
    responsibilities: [
      "Led full-stack feature delivery using React.js, Next.js, TypeScript, Redux Toolkit, React Query, Node.js, Express.js, and API-driven application architecture.",
      "Developed and integrated REST and GraphQL APIs using Node.js/Express.js and Apollo tooling, supporting authentication, data handling, frontend-backend integration, and cross-system troubleshooting.",
      "Owned GitLab delivery workflows from feature branching, merge requests, and peer reviews through CI/CD pipelines, build/test validation, environment deployments, staged releases, production validation, monitoring, and troubleshooting.",
      "Built secure, accessible, production-ready applications and implemented automated unit, component, and end-to-end testing using Jest, React Testing Library, Vitest, Playwright, Cypress, and MSW.",
      "Contributed to AI-powered capabilities, AWS solutions, authentication, cross-system debugging, production support, and continuous engineering improvements.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Redux Toolkit",
      "React Query",
      "Node.js",
      "Express.js",
      "REST APIs",
      "GraphQL",
      "Apollo",
      "GitLab CI/CD",
      "AWS",
      "Jest",
      "React Testing Library",
      "Vitest",
      "Playwright",
      "Cypress",
      "MSW",
    ],
    focus: [
      "Full-stack feature delivery",
      "Micro Frontend Architecture",
      "Performance optimization",
      "Reusable component libraries",
      "Release ownership",
      "Automated testing",
    ],
    achievements: [
      "Improved application performance by approximately 30–35% through code splitting, lazy loading, SSR/SSG/ISR, rendering optimization, memoization, bundle optimization, and efficient state management.",
      "Designed and implemented Micro Frontend Architecture to enable parallel team development, reduce inter-team dependencies, and improve independent feature delivery.",
      "Built reusable component libraries and shared utilities that reduced development rework by approximately 20–25% and improved consistency across application modules.",
    ],
    projects: [],
    pending: ["Confirm whether the Quality Inspection Platform belongs to this role"],
  },
  {
    id: "nagarro-engineer",
    company: "Nagarro",
    title: "Engineer",
    period: { start: "2022-04", end: "2024-07" },
    location: null,
    summary: null,
    responsibilities: [
      "Developed scalable web application features using React.js, Next.js, JavaScript, TypeScript, Redux Toolkit, and React Query with reusable and maintainable application patterns.",
      "Developed and integrated REST APIs and backend services using Node.js and Express.js, supporting frontend workflows, API integration, validation, and end-to-end feature delivery.",
      "Worked with GraphQL and API-driven architecture, integrating backend data with frontend state and data-fetching workflows.",
      "Participated in code reviews, debugging, refactoring, automated testing, Git workflows, CI/CD processes, and Agile/Scrum delivery.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "JavaScript",
      "TypeScript",
      "Redux Toolkit",
      "React Query",
      "Node.js",
      "Express.js",
      "REST APIs",
      "GraphQL",
    ],
    focus: ["Feature development", "API integration", "GraphQL data fetching", "Code quality"],
    achievements: [],
    projects: [],
    pending: ["Key achievements"],
  },
  {
    id: "web-corporation",
    company: "Web Corporation",
    title: "Software Developer",
    period: { start: "2019-05", end: "2022-03" },
    location: "Delhi, India",
    summary: null,
    responsibilities: [
      "Developed scalable web applications using React.js, Redux, Next.js, and JavaScript with reusable components and maintainable application architecture.",
      "Integrated RESTful APIs and backend services into React.js and Next.js applications, implementing data-fetching, error-handling, loading, and state-management patterns.",
      "Contributed to full-stack feature development using Node.js and Express.js, supporting backend API development, frontend integration, and end-to-end delivery.",
      "Implemented automated testing using Jest and React Testing Library and participated in code reviews, debugging, refactoring, and Git-based development workflows.",
    ],
    technologies: [
      "React.js",
      "Redux",
      "Next.js",
      "JavaScript",
      "Node.js",
      "Express.js",
      "REST APIs",
      "Jest",
      "React Testing Library",
    ],
    focus: [
      "React & Next.js applications",
      "API integration",
      "Performance optimization",
      "Automated testing",
    ],
    achievements: [
      "Improved application performance through rendering optimization, efficient state updates, code splitting, lazy loading, and frontend optimization techniques.",
    ],
    projects: [],
    pending: [],
  },
]);
