import { defineContent } from "@/lib/schemas/common";
import { profileSchema } from "@/lib/schemas/content";

export const profile = defineContent("profile", profileSchema, {
  name: "Deepak Gupta",
  title: "Senior Full-Stack Engineer",
  subtitle: "Frontend, backend, APIs and cloud",
  experienceYears: "7+",
  headline: "Building scalable web applications, from UI to cloud.",
  intro:
    "I'm Deepak Gupta, a Senior Full-Stack Engineer with 7+ years of experience building scalable, secure web applications end to end — React and Next.js interfaces, Node.js services and APIs, and the cloud they run on.",
  location: "Delhi NCR, India",
  availability: "Immediate Joiner",
  workModes: ["Remote", "Hybrid", "Relocation"],
  timezone: "IST (UTC+5:30)",
  primaryStack: ["React.js", "Next.js", "Node.js", "TypeScript"],
  secondaryStack: [
    "Express.js",
    "NestJS",
    "REST APIs",
    "GraphQL",
    "AWS",
    "Docker",
    "Kubernetes",
    "GitLab CI/CD",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
  ],
  backendStack: ["Node.js", "Express.js", "NestJS", "REST", "GraphQL"],
  focusAreas: [
    "Full-Stack Engineering",
    "Scalable Web Applications",
    "API Development",
    "Frontend Architecture",
    "Micro Frontends",
    "Microservices",
    "Cloud & DevOps",
    "Performance Optimization",
    "Application Security",
    "Automated Testing",
    "Accessibility",
    "AI-Assisted Engineering",
  ],
  heroBadges: ["7+ Years Experience", "React.js", "Next.js", "Node.js", "TypeScript", "AWS"],
  education: {
    degree: "B.Tech",
    field: "Electronics & Communication Engineering",
    year: "2019",
    institution: "Dr. A.P.J. Abdul Kalam Technical University (AKTU)",
  },
  story: [
    {
      id: "origin",
      title: "From electronics to the web",
      body: "I graduated in Electronics & Communication Engineering in 2019 and started my career building web applications. Systems thinking from hardware carried over: I like knowing how every layer connects.",
      draft: true,
    },
    {
      id: "specialization",
      title: "Full-stack, end to end",
      body: "I build across the whole stack: React, Next.js and TypeScript on the frontend; Node.js, Express and NestJS services behind REST and GraphQL APIs; and AWS, Docker and GitLab CI/CD to ship and run them. I like owning a feature from the requirement through architecture, testing, release and monitoring.",
      draft: true,
    },
    {
      id: "product",
      title: "Product before pixels",
      body: "I start from the user's workflow and the business constraint, then choose the simplest architecture that serves both. Tradeoffs get written down so the team can revisit them.",
      draft: true,
    },
    {
      id: "now",
      title: "Current focus",
      body: "Senior full-stack roles where architecture, performance and product quality matter — using AI tools to move faster while keeping review, testing and production validation firmly human.",
      draft: true,
    },
  ],
  pending: ["Review and approve the About story wording"],
});
